int init;
static char get_choice();
static int set_sorted(int v);
static void set_LSIZE(int v);
void setLSize();
void fillRand();
void fillAsc();
void fillDsc();
void fillArray();
void creArr();
int linSrch(int v);
void LSrch();
int binSrch(int array[], int v, int low, int high);
void BSrch();
void bstBest();
void bstWorst();
void bstRand();
void addBST();
void BST();      
void bSort(); 
void unlink();     	  
void insSort();
int Partition(int array[], int a, int b);
void quickSort(int v[], int a, int b);
void qSort();
void disp();
void prntBST();